import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db/prisma';
import { attemptPullRequestApproval, performPullRequestReview } from '@/lib/github/review-boundary';
import { attemptMergeAsAgent, requestHumanMergeApproval } from '@/lib/github/merge-boundary';
import { evaluateProtectedBranchWrite, evaluateWorkspaceWrite } from '@/lib/github/negative-controls';
import { getAgentTrustState } from '@/lib/github/trust-lifecycle';

type Check={name:string;passed:boolean;details:unknown};
export async function POST(request:Request){try{const{executionId,pullRequestNumber}=await request.json();if(!executionId||!pullRequestNumber)return NextResponse.json({ok:false,error:'executionId and pullRequestNumber are required.'},{status:400});const execution=await prisma.execution.findUnique({where:{id:executionId},include:{task:{include:{repository:true}},agent:true}});if(!execution)return NextResponse.json({ok:false,error:'Execution not found.'},{status:404});const reviewer=await prisma.agent.findFirst({where:{id:{not:execution.agentId},status:'ACTIVE',grants:{some:{capability:'review.approve',effect:'ALLOW'}}}});if(!reviewer)throw new Error('Independent reviewer not found.');const checks:Check[]=[];
 const self=await attemptPullRequestApproval(executionId,Number(pullRequestNumber),execution.agentId);checks.push({name:'self-approval denied before GitHub',passed:!self.allowed&&self.reasonCode==='policy.self_approval_denied'&&self.githubRequestSent===false,details:self});
 const protectedWrite=await evaluateProtectedBranchWrite(executionId,execution.task.repository.defaultBranch);checks.push({name:'protected branch write denied',passed:!protectedWrite.allowed&&protectedWrite.reasonCode==='policy.protected_branch_write_denied'&&protectedWrite.githubRequestSent===false,details:protectedWrite});
 const cross=await evaluateWorkspaceWrite(executionId,`${executionId}-foreign`);checks.push({name:'cross-workspace write denied',passed:!cross.allowed&&cross.reasonCode==='policy.cross_workspace_write_denied'&&cross.writeAttempted===false,details:cross});
 const implementationMerge=await attemptMergeAsAgent(executionId,Number(pullRequestNumber),execution.agentId);checks.push({name:'implementation merge denied before GitHub',passed:!implementationMerge.allowed&&implementationMerge.githubRequestSent===false&&implementationMerge.reasonCode==='policy.implementation_agent_merge_denied',details:implementationMerge});
 const reviewerMerge=await attemptMergeAsAgent(executionId,Number(pullRequestNumber),reviewer.id);checks.push({name:'reviewer merge denied before GitHub',passed:!reviewerMerge.allowed&&reviewerMerge.githubRequestSent===false&&reviewerMerge.reasonCode==='policy.agent_merge_denied',details:reviewerMerge});
 const review=await performPullRequestReview(executionId,Number(pullRequestNumber),reviewer.id,'REVIEW');checks.push({name:'independent review principal enforced',passed:review.allowed&&review.reviewGitHubApp==='gitagent-review'&&review.reviewerAgentId===reviewer.id&&review.implementationAgentId===execution.agentId,details:review});
 const approval=await performPullRequestReview(executionId,Number(pullRequestNumber),reviewer.id,'APPROVE');checks.push({name:'independent approval enforced',passed:approval.allowed&&approval.approvalSubmitted===true&&approval.reviewGitHubApp==='gitagent-review',details:approval});
 const mergeApproval=await requestHumanMergeApproval(executionId,Number(pullRequestNumber));checks.push({name:'human merge approval required',passed:(mergeApproval.status==='PENDING'||mergeApproval.status==='APPROVED')&&mergeApproval.action===`pr.merge:${pullRequestNumber}`,details:{id:mergeApproval.id,status:mergeApproval.status,action:mergeApproval.action}});
 const trust=await getAgentTrustState(execution.agentId);checks.push({name:'trust state observable',passed:['TRUSTED','RESTRICTED','QUARANTINED'].includes(trust),details:{trustState:trust}});
 const failed=checks.filter(c=>!c.passed);await prisma.auditEvent.create({data:{taskId:execution.taskId,executionId,eventType:'security.suite.completed',actorType:'system',actorId:'gitagent',payload:{pullRequestNumber,passed:failed.length===0,totalChecks:checks.length,failedChecks:failed.map(c=>c.name),policyVersion:'2026-09-16.1'}}});return NextResponse.json({ok:true,passed:failed.length===0,summary:{total:checks.length,passed:checks.length-failed.length,failed:failed.length},executionId,pullRequestNumber,checks});}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:String(error)},{status:500});}}
