import { prisma } from '@/lib/db/prisma';
import { createReviewInstallationToken, isReviewAppConfigured } from './review-auth';
const API='https://api.github.com', VERSION='2022-11-28';
type ReviewAction='REVIEW'|'APPROVE';
async function github<T>(url:string,token:string,init:RequestInit={}):Promise<T>{const r=await fetch(url,{...init,cache:'no-store',headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':VERSION,'User-Agent':'GitAgent-Review','Content-Type':'application/json',...init.headers}});if(!r.ok)throw new Error(`GitHub API ${r.status}: ${(await r.text()).slice(0,500)}`);return await r.json() as T;}
export async function performPullRequestReview(executionId:string,pullRequestNumber:number,actorAgentId:string,action:ReviewAction){
 const execution=await prisma.execution.findUnique({where:{id:executionId},include:{task:{include:{repository:true}},agent:true}});if(!execution)throw new Error('Execution not found.');const repo=execution.task.repository,repository=`${repo.owner}/${repo.name}`;
 if(actorAgentId===execution.agentId){await prisma.auditEvent.create({data:{taskId:execution.taskId,executionId,eventType:'policy.review.denied',actorType:'agent',actorId:actorAgentId,payload:{repository,pullRequestNumber,decision:'DENY',reasonCode:'policy.self_approval_denied',githubRequestSent:false,policyVersion:'2026-09-16.1'}}});return{allowed:false as const,decision:'DENY',reasonCode:'policy.self_approval_denied',githubRequestSent:false};}
 const reviewer=await prisma.agent.findUnique({where:{id:actorAgentId}});if(!reviewer||reviewer.status!=='ACTIVE')throw new Error('Review agent is not active.');const grant=await prisma.capabilityGrant.findFirst({where:{agentId:actorAgentId,capability:'review.approve',effect:'ALLOW',OR:[{resource:'*'},{resource:repo.id},{resource:repository}],AND:[{OR:[{expiresAt:null},{expiresAt:{gt:new Date()}}]}]}});if(!grant)return{allowed:false as const,decision:'DENY',reasonCode:'policy.capability_not_granted',githubRequestSent:false};
 if(!isReviewAppConfigured())return{allowed:true as const,decision:'ALLOW',reasonCode:'policy.review_app_not_configured',githubRequestSent:false};
 const eventType=action==='REVIEW'?'github.review.created':'github.review.approved';const prior=await prisma.auditEvent.findFirst({where:{executionId,actorId:actorAgentId,eventType},orderBy:{createdAt:'desc'}});if(prior){const p=prior.payload as Record<string,any>;return{allowed:true as const,decision:'ALLOW',reasonCode:action==='REVIEW'?'policy.independent_review_allowed':'policy.independent_approval_allowed',githubRequestSent:false,idempotentReplay:true,approvalSubmitted:action==='APPROVE',githubReviewId:p.githubReviewId,githubReviewState:p.githubReviewState,reviewGitHubApp:p.reviewGitHubApp,reviewerAgentId:actorAgentId,implementationAgentId:execution.agentId,capabilityGrantId:grant.id};}
 if(action==='APPROVE'){const review=await prisma.auditEvent.findFirst({where:{executionId,actorId:actorAgentId,eventType:'github.review.created'}});if(!review)return{allowed:false as const,decision:'DENY',reasonCode:'policy.review_required_before_approval',githubRequestSent:false};}
 const installation=await createReviewInstallationToken();const event=action==='REVIEW'?'COMMENT':'APPROVE';const result=await github<{id:number;state:string;html_url:string}>(`${API}/repos/${repo.owner}/${repo.name}/pulls/${pullRequestNumber}/reviews`,installation.token,{method:'POST',body:JSON.stringify({event,body:action==='REVIEW'?`GitAgent independent review by ${reviewer.name} (${reviewer.id}).`:`GitAgent independent approval by ${reviewer.name} (${reviewer.id}).`})});
 const reasonCode=action==='REVIEW'?'policy.independent_review_allowed':'policy.independent_approval_allowed';await prisma.auditEvent.create({data:{taskId:execution.taskId,executionId,eventType,actorType:'agent',actorId:actorAgentId,payload:{repository,pullRequestNumber,githubReviewId:result.id,githubReviewState:result.state,githubReviewUrl:result.html_url,implementationAgentId:execution.agentId,reviewerAgentId:actorAgentId,reviewGitHubApp:installation.appSlug,capabilityGrantId:grant.id,decision:'ALLOW',reasonCode,policyVersion:'2026-09-16.1',metadata:{githubRequestSent:true,separateGitHubPrincipal:true,writableImplementationWorkspaceInherited:false}}}});
 return{allowed:true as const,decision:'ALLOW',reasonCode,githubRequestSent:true,approvalSubmitted:action==='APPROVE',githubReviewId:result.id,githubReviewState:result.state,githubReviewUrl:result.html_url,reviewGitHubApp:installation.appSlug,reviewerAgentId:actorAgentId,implementationAgentId:execution.agentId,capabilityGrantId:grant.id};
}
export async function attemptPullRequestApproval(executionId:string,pullRequestNumber:number,actorAgentId:string){const prior=await prisma.auditEvent.findFirst({where:{executionId,actorId:actorAgentId,eventType:'github.review.created'}});return performPullRequestReview(executionId,pullRequestNumber,actorAgentId,prior?'APPROVE':'REVIEW');}
